/**
 * PARTH ASSISTANT AI — System Strings Localization Dictionary
 * Provides complete UI system text across all 11 supported languages.
 */

export const UI_LOCALIZED_STRINGS = {
  en: {
    greeting: "Hi, I'm Parth Assistant AI.\nHow can I help you today?",
    speak: "🎤 Speak",
    type: "⌨ Type",
    language: "🌐 Language",
    listening: "Listening...",
    thinking: "Parth is processing...",
    analyzing: "Analyzing request intent & permissions...",
    askPlaceholder: "Ask Parth...",
    closeDashboard: "Close Dashboard",
    fullDashboard: "Full Dashboard",
    dynamicWorkspaceTitle: "Dynamic Workspace",
    dynamicWorkspaceDesc: "Ask Parth Assistant AI any question. The relevant component will appear here automatically.",
    retryText: "Please try again.",
    errorText: "Something went wrong. Please check connection.",
    permissionDeniedText: "Microphone permission denied."
  },
  hi: {
    greeting: "नमस्ते, मैं पार्थ असिस्टेंट AI हूँ।\nआज मैं आपकी क्या सहायता कर सकता हूँ?",
    speak: "🎤 बोलें",
    type: "⌨ टाइप करें",
    language: "🌐 भाषा",
    listening: "सुन रहा हूँ...",
    thinking: "पार्थ सोच रहा है...",
    analyzing: "अनुरोध का विश्लेषण किया जा रहा है...",
    askPlaceholder: "पार्थ से पूछें...",
    closeDashboard: "डैशबोर्ड बंद करें",
    fullDashboard: "पूरा डैशबोर्ड",
    dynamicWorkspaceTitle: "डायनामिक वर्कस्पेस",
    dynamicWorkspaceDesc: "पार्थ असिस्टेंट AI से कोई भी प्रश्न पूछें। संबंधित कंपोनेंट यहाँ दिखाई देगा।",
    retryText: "कृपया पुनः प्रयास करें।",
    errorText: "कुछ समस्या हुई है। कृपया कनेक्शन जांचें।",
    permissionDeniedText: "माइक्रोफोन अनुमति अस्वीकृत।"
  },
  ta: {
    greeting: "வணக்கம், நான் பார்த் அசிஸ்டன்ட் AI.\nஇன்று உங்களுக்கு எப்படி உதவ முடியும்?",
    speak: "🎤 பேசுங்கள்",
    type: "⌨ தட்டச்சு செய்",
    language: "🌐 மொழி",
    listening: "கேட்கிறது...",
    thinking: "பார்த் சிந்திக்கிறது...",
    analyzing: "கோரிக்கை பகுப்பாய்வு செய்யப்படுகிறது...",
    askPlaceholder: "பார்திடம் கேளுங்கள்...",
    closeDashboard: "மூடு",
    fullDashboard: "முழு டாஷ்போர்டு",
    dynamicWorkspaceTitle: "டைனமிக் பணிப்பகுதி",
    dynamicWorkspaceDesc: "ஏதேனும் கேள்வி கேளுங்கள். தொடர்புள்ள கூறு இங்கே தோன்றும்.",
    retryText: "மீண்டும் முயற்சிக்கவும்.",
    errorText: "ஏதோ தவறு நடந்துவிட்டது.",
    permissionDeniedText: "மைக்ரோஃபோன் அனுமதி மறுக்கப்பட்டது."
  },
  te: {
    greeting: "నమస్కారం, నేను పార్థ్ అసిస్టెంట్ AI.\nనేను మీకు ఎలా సహాయపడగలను?",
    speak: "🎤 మాట్లాడండి",
    type: "⌨ టైప్ చేయండి",
    language: "🌐 భాష",
    listening: "వింటోంది...",
    thinking: "పార్థ్ ఆలోచిస్తోంది...",
    analyzing: "అభ్యర్థన విశ్లేషించబడుతోంది...",
    askPlaceholder: "పార్థ్ నడగండి...",
    closeDashboard: "మూసివేయి",
    fullDashboard: "పూర్తి డాష్‌బోర్డ్",
    dynamicWorkspaceTitle: "డైనమిక్ వర్క్‌స్పేస్",
    dynamicWorkspaceDesc: "ఏదైనా ప్రశ్న అడగండి. సంబంధిత విడ్జెట్ ఇక్కడ కనిపిస్తుంది.",
    retryText: "దయచేసి మళ్లీ ప్రయత్నించండి.",
    errorText: "ఏదో పొరపాటు జరిగింది.",
    permissionDeniedText: "మైక్రోఫోన్ అనుమతి నిరాకరించబడింది."
  },
  mr: {
    greeting: "नमस्कार, मी पार्थ असिस्टंट AI आहे.\nआज मी तुम्हाला कशी मदत करू शकतो?",
    speak: "🎤 बोला",
    type: "⌨ टाईप करा",
    language: "🌐 भाषा",
    listening: "ऐकत आहे...",
    thinking: "पार्थ विचार करत आहे...",
    analyzing: "विनंतीचे विश्लेषण केले जात आहे...",
    askPlaceholder: "पार्थला विचारा...",
    closeDashboard: "डॅशबोर्ड बंद करा",
    fullDashboard: "संपूर्ण डॅशबोर्ड",
    dynamicWorkspaceTitle: "डायनामिक वर्कस्पेस",
    dynamicWorkspaceDesc: "पार्थ असिस्टंट AI ला कोणताही प्रश्न विचारा. संबंधित घटक येथे दिसेल.",
    retryText: "कृपया पुन्हा प्रयत्न करा.",
    errorText: "काहीतरी चूक झाली आहे.",
    permissionDeniedText: "मायक्रोफोन परवानगी नाकारली."
  },
  bn: {
    greeting: "নমস্কার, আমি পার্থ অ্যাসিস্ট্যান্ট AI।\nআজ আপনাকে কীভাবে সাহায্য করতে পারি?",
    speak: "🎤 বলুন",
    type: "⌨ টাইপ করুন",
    language: "🌐 ভাষা",
    listening: "শুনছি...",
    thinking: "পার্থ চিন্তা করছে...",
    analyzing: "অনুরোধ বিশ্লেষণ করা হচ্ছে...",
    askPlaceholder: "পার্থকে জিজ্ঞাসা করুন...",
    closeDashboard: "ড্যাশবোর্ড বন্ধ করুন",
    fullDashboard: "সম্পূর্ণ ড্যাশবোর্ড",
    dynamicWorkspaceTitle: "ডায়নামিক ওয়ার্কস্পেস",
    dynamicWorkspaceDesc: "যেকোনো প্রশ্ন জিজ্ঞাসা করুন। প্রাসঙ্গিক উপাদান এখানে প্রদর্শিত হবে।",
    retryText: "পুনরায় চেষ্টা করুন।",
    errorText: "কিছু ত্রুটি ঘটেছে।",
    permissionDeniedText: "মাইক্রোফোন অনুমতি প্রত্যাখ্যাত।"
  },
  gu: {
    greeting: "નમસ્તે, હું પાર્થ આસિસ્ટન્ટ AI છું.\nઆજે હું તમને કેવી રીતે મદદ કરી શકું?",
    speak: "🎤 બોલો",
    type: "⌨ ટાઇપ કરો",
    language: "🌐 ભાષા",
    listening: "સાંભળી રહ્યું છે...",
    thinking: "પાર્થ વિચારી રહ્યું છે...",
    analyzing: "વિનંતી વિશ્લેષણ થઈ રહ્યું છે...",
    askPlaceholder: "પાર્થને પૂછો...",
    closeDashboard: "ડેશબોર્ડ બંધ કરો",
    fullDashboard: "સંપૂર્ણ ડેશબોર્ડ",
    dynamicWorkspaceTitle: "ડાયનેમિક વર્કસ્પેસ",
    dynamicWorkspaceDesc: "કોઈપણ પ્રશ્ન પૂછો. સંબંધિત ઘટક અહીં દેખાશે.",
    retryText: "મહેરબાની કરીને ફરી પ્રયાસ કરો.",
    errorText: "કંઈક ખોટું થયું છે.",
    permissionDeniedText: "માઇક્રોફોન પરવાનગી અસ્વીકાર થઈ."
  },
  pa: {
    greeting: "ਸਤਿ ਸ਼੍ਰੀ ਅਕਾਲ, ਮੈਂ ਪਾਰਥ ਅਸਿਸਟੈਂਟ AI ਹਾਂ।\nਅੱਜ ਮੈਂ ਤੁਹਾਡੀ ਕੀ ਮਦਦ ਕਰ ਸਕਦਾ ਹਾਂ?",
    speak: "🎤 ਬੋਲੋ",
    type: "⌨ ਟਾਈਪ ਕਰੋ",
    language: "🌐 ਭਾਸ਼ਾ",
    listening: "ਸੁਣ ਰਿਹਾ ਹਾਂ...",
    thinking: "ਪਾਰਥ ਸੋਚ ਰਿਹਾ ਹੈ...",
    analyzing: "ਬੇਨਤੀ ਦੀ ਜਾਂਚ ਕੀਤੀ ਜਾ ਰਹੀ ਹੈ...",
    askPlaceholder: "ਪਾਰਥ ਤੋਂ ਪੁੱਛੋ...",
    closeDashboard: "ਡੈਸ਼ਬੋਰਡ ਬੰਦ ਕਰੋ",
    fullDashboard: "ਪੂਰਾ ਡੈਸ਼ਬੋਰਡ",
    dynamicWorkspaceTitle: "ਡਾਇਨਾਮਿਕ ਵਰਕਸਪੇਸ",
    dynamicWorkspaceDesc: "ਕੋਈ ਵੀ ਸਵਾਲ ਪੁੱਛੋ। ਸੰਬੰਧਿਤ ਜਾਣਕਾਰੀ ਇੱਥੇ ਦਿਖਾਈ ਦੇਵੇਗੀ।",
    retryText: "ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    errorText: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ।",
    permissionDeniedText: "ਮਾਈਕ੍ਰੋਫੋਨ ਦੀ ਇਜਾਜ਼ਤ ਨਹੀਂ ਮਿਲੀ।"
  },
  kn: {
    greeting: "ನಮಸ್ಕಾರ, ನಾನು ಪಾರ್ಥ್ ಅಸಿಸ್ಟೆಂಟ್ AI.\nಇಂದು ನಾನು ನಿಮಗೆ ಹೇಗೆ ಸಹಾಯ ಮಾಡಲಿ?",
    speak: "🎤 ಮಾತನಾಡಿ",
    type: "⌨ ಟೈಪ್ ಮಾಡಿ",
    language: "🌐 ಭಾಷೆ",
    listening: "ಕೇಳಿಸಿಕೊಳ್ಳುತ್ತಿದೆ...",
    thinking: "ಪಾರ್ಥ್ ಯೋಚಿಸುತ್ತಿದೆ...",
    analyzing: "ವಿನಂತಿಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    askPlaceholder: "ಪಾರ್ಥ್ ಅವರಲ್ಲಿ ಕೇಳಿ...",
    closeDashboard: "ಮುಚ್ಚಿ",
    fullDashboard: "ಸಂಪೂರ್ಣ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    dynamicWorkspaceTitle: "ಡೈನಾಮಿಕ್ ವರ್ಕ್‌ಸ್ಪೇಸ್",
    dynamicWorkspaceDesc: "ಯಾವುದೇ ಪ್ರಶ್ನೆಯನ್ನು ಕೇಳಿ. ಸಂಬಂಧಿತ ಭಾಗವು ಇಲ್ಲಿ ಕಾಣಿಸಿಕೊಳ್ಳುತ್ತದೆ.",
    retryText: "ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    errorText: "ಏನೋ ತಪ್ಪಾಗಿದೆ.",
    permissionDeniedText: "ಮೈಕ್ರೊಫೋನ್ ಅನುಮತಿಯನ್ನು ನಿರಾಕರಿಸಲಾಗಿದೆ."
  },
  ml: {
    greeting: "നമസ്കാരം, ഞാൻ പാർത്ഥ് അസിസ്റ്റന്റ് AI ആണ്.\nഇന്ന് ഞാൻ നിങ്ങളെ എങ്ങനെ സഹായിക്കണം?",
    speak: "🎤 സംസാരിക്കൂ",
    type: "⌨ ടൈപ്പ് ചെയ്യൂ",
    language: "🌐 ഭാഷ",
    listening: "ശ്രദ്ധിക്കുന്നു...",
    thinking: "പാർത്ഥ് ചിന്തിക്കുന്നു...",
    analyzing: "അഭ്യർത്ഥന പരിശോധിക്കുന്നു...",
    askPlaceholder: "പാർത്ഥിനോട് ചോദിക്കൂ...",
    closeDashboard: "ഡാഷ്‌ബോർഡ് അടയ്ക്കൂ",
    fullDashboard: "പൂർണ്ണ ഡാഷ്‌ബോർഡ്",
    dynamicWorkspaceTitle: "ഡൈനാമിക് വർക്ക്‌സ്പേസ്",
    dynamicWorkspaceDesc: "ഏത് ചോദ്യവും ചോദിക്കൂ. അനുബന്ധ വിവരങ്ങൾ ഇവിടെ കാണാം.",
    retryText: "ദയവായി വീണ്ടും ശ്രമിക്കൂ.",
    errorText: "എന്തോ തകരാർ സംഭവിച്ചു.",
    permissionDeniedText: "മൈക്രോഫോൺ അനുമതി നിരസിക്കപ്പെട്ടു."
  },
  ur: {
    greeting: "السلام علیکم! میں پارتھ اسسٹنٹ AI ہوں۔\nآج میں آپ کی کیا مدد کر سکتا ہوں؟",
    speak: "🎤 بولیں",
    type: "⌨ ٹائپ کریں",
    language: "🌐 زبان",
    listening: "سن رہا ہوں...",
    thinking: "پارتھ سوچ رہا ہے...",
    analyzing: "درخواست کی تصدیق کی جا رہی ہے...",
    askPlaceholder: "پارتھ سے پوچھیں...",
    closeDashboard: "ڈیش بورڈ بند کریں",
    fullDashboard: "مکمل ڈیش بورڈ",
    dynamicWorkspaceTitle: "ڈائنامک ورک اسپیس",
    dynamicWorkspaceDesc: "پارتھ اسسٹنٹ AI سے کوئی بھی سوال پوچھیں۔ متعلقہ کارڈ یہاں نظر آئے گا۔",
    retryText: "براہ کرم دوبارہ کوشش کریں۔",
    errorText: "کچھ غلط ہو گیا۔",
    permissionDeniedText: "مائیکروفون کی اجازت نہیں ملی۔"
  }
};

export function getUIString(lang, key) {
  const dict = UI_LOCALIZED_STRINGS[lang] || UI_LOCALIZED_STRINGS.en;
  return dict[key] || UI_LOCALIZED_STRINGS.en[key] || "";
}
